### ISSUE TITLE
No Code

### ISSUE THREAD

**Issue by MickCG** [CodeMazeBlog/BlazorWebAssembly#5]
OK, hope I have not made a big mistake. I see this repository is 3 years old, so the course is not exactly current maybe? But anyway looks like this repository has no code in it, not good?

**Comment by CodeMazeBlog** [comment]
Hey @MickCG, every module has the starting branch and the end branch. You can follow along by picking the branch you want for each chapter, whether you work on your own or use our code. Do check the branches, we've added an explanation of where to find the code in the introductory material.
For example, the code for the module 2 end is [here](https://github.com/CodeMazeBlog/BlazorWebAssembly/tree/module2-end).
